return {
  uv_buf_t = require 'uv/ctypes/uv_buf_t',
  uv_check_t = require 'uv/ctypes/uv_check_t',
  uv_connect_t = require 'uv/ctypes/uv_connect_t',
  uv_fs_t = require 'uv/ctypes/uv_fs_t',
  uv_getaddrinfo_t = require 'uv/ctypes/uv_getaddrinfo_t',
  uv_handle_t = require 'uv/ctypes/uv_handle_t',
  uv_idle_t = require 'uv/ctypes/uv_idle_t',
  uv_loop_t = require 'uv/ctypes/uv_loop_t',
  uv_prepare_t = require 'uv/ctypes/uv_prepare_t',
  uv_process_t = require 'uv/ctypes/uv_process_t',
  uv_process_options_t = require 'uv/ctypes/uv_process_options_t',
  uv_signal_t = require 'uv/ctypes/uv_signal_t',
  uv_stream_t = require 'uv/ctypes/uv_stream_t',
  uv_tcp_t = require 'uv/ctypes/uv_tcp_t',
  uv_timer_t = require 'uv/ctypes/uv_timer_t',
  uv_write_t = require 'uv/ctypes/uv_write_t',
}
